export default{
    products: [{
            _id:123,
            name: 'Slim Shirt',
            category: 'Shirts',
            image: '/images/d1.jpg',
            price: 60,
            brand: 'Nike',
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent ut justo feugiat, gravida.',
            countInStock: 0,
        },
        {
            _id:133,
            name: 'Fit Shirt',
            category: 'Shirts',
            image: '/images/d1.jpg',
            price: 89,
            brand: 'Nike',
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent ut justo feugiat, gravida.',
            countInStock: 9,
        },
        {
            _id:143,
            name: 'Best Pants',
            category: 'Pants',
            image: '/images/d1.jpg',
            price: 100,
            brand: 'Nike',
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent ut justo feugiat, gravida.',
            countInStock: 7,
        },{
            _id:153,
            name: 'Fit Shirt',
            category: 'Shirts',
            image: '/images/d1.jpg',
            price: 89,
            brand: 'Nike',
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent ut justo feugiat, gravida.',
            countInStock: 15,
        },{
            _id:163,
            name: 'Fit Shirt',
            category: 'Shirts',
            image: '/images/d1.jpg',
            price: 89,
            brand: 'Nike',
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent ut justo feugiat, gravida.',
            countInStock: 5,
        },{
            _id:173,
            name: 'Fit Shirt',
            category: 'Shirts',
            image: '/images/d1.jpg',
            price: 89,
            brand: 'Nike',
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent ut justo feugiat, gravida.',
            countInStock: 10,
        },{
            _id:183,
            name: 'Fit Shirt',
            category: 'Shirts',
            image: '/images/d1.jpg',
            price: 89,
            brand: 'Nike',
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent ut justo feugiat, gravida.',
            countInStock: 21,
        },{
            _id:193,
            name: 'Fit Shirt',
            category: 'Shirts',
            image: '/images/d1.jpg',
            price: 89,
            brand: 'Nike',
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent ut justo feugiat, gravida.',
            countInStock: 16,
        },{
            _id:293,
            name: 'Fit Shirt',
            category: 'Shirts',
            image: '/images/d1.jpg',
            price: 89,
            brand: 'Nike',
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent ut justo feugiat, gravida.',
            countInStock: 1,
        },{
            _id:393,
            name: 'Fit Shirt',
            category: 'Shirts',
            image: '/images/d1.jpg',
            price: 89,
            brand: 'Nike',
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent ut justo feugiat, gravida.',
            countInStock: 2,
        },{
            _id:493,
            name: 'Fit Shirt',
            category: 'Shirts',
            image: '/images/d1.jpg',
            price: 89,
            brand: 'Nike',
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent ut justo feugiat, gravida.',
            countInStock: 7,
        },{
            _id:593,
            name: 'Fit Shirt',
            category: 'Shirts',
            image: '/images/d1.jpg',
            price: 89,
            brand: 'Nike',
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent ut justo feugiat, gravida.',
            countInStock: 12,
        },]
}